# Generated by Django 3.1.6 on 2021-02-24 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poi',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=100)),
                ('lat', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(blank=True, max_length=511, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.poi')),
            ],
        ),
    ]
