# Generated by Django 3.1.6 on 2021-03-19 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=511, null=True)),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.poi')),
            ],
        ),
    ]
