# Generated by Django 3.1.6 on 2021-03-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='poi',
        ),
        migrations.AddField(
            model_name='review',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
